#! /usr/bin/python3

def suffixe(string):
  l=len(string)
  pi={}
  pi[1]=0
  k=0
  for q in range(1,l):
    while (k>0) and string[k]!=string[q]:
      k=pi[k]
    if string[k]==string[q]:
      k+=1
    pi[q+1]=k
  return(pi)

def find(T,P,pi):
  i=0
  j=0
  lT=len(T)
  lP=len(P)
  compte=0
  while i<lP and j<lT:
    if T[j]==P[i]:
      i+=1
      j+=1
      if i==lP:
        compte+=1
        i=0
    else:  
      j-=pi[i+1]-1
      i=0  
  return str(compte)+" occurence(s)"
        
   

pi=suffixe('raphael')
pi_2=suffixe('aca')

print(find('bonjour je mappelle raphel','raphael',pi))
  
